### PR TITLE
Add code for embed

### PR DESCRIPTION
**Pull request by duncanjbrown**
This lacks a nice public API.

At the moment the user has to `new` up an `Article`, a `PublisherAccount` and an `HtmlEmbed` for it all to work.

It is also hardcoded to point to `demo.1pass.me`.

### CODE REVIEW

**Comment by benilovj** [comment]
I don't think that the embed and the JS include should be coupled in the same view. Could those be two separate things?

**Comment by benilovj** [comment]
> At the moment the user has to new up an Article, a PublisherAccount and an HtmlEmbed for it all to work.

Maybe we could add `publisherAccount#embedFor(article)`? That saves the consumer from having to know so much about the inner workings of this package...

**Comment by duncanjbrown** [comment]
or even at a higher level? could there be just one object that takes keys
and environment and provides the whole public API?

**Comment by benilovj** [comment]
We could add "environment" to PublisherAccount. We could rename this class later as it gains more functionality. I'm not as fussed about getting the naming correct right now, as we have all the consumers under our control...

**Comment by duncanjbrown** [comment]
Added a commit to split the embed

**Pull request merged**
